export const ACTIONS = {
  TOGGLE_THEME: "TOGGLE_THEME",
  TOGGLE_LANGUAGE: "TOGGLE_LANGUAGE",

  FETCH_PORTFOLIO_START: "FETCH_PORTFOLIO_START",
  FETCH_PORTFOLIO_SUCCESS: "FETCH_PORTFOLIO_SUCCESS",
  FETCH_PORTFOLIO_ERROR: "FETCH_PORTFOLIO_ERROR",
};
